# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Gemini code reviews configuration; see
# https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github.

code_review:
  # Valid levels are LOW, MEDIUM, HIGH, or CRITICAL.
  comment_severity_threshold: MEDIUM

  pull_request_opened:
    code_review: true

    # Make the gemini PR comments more terse.
    help: false
    summary: false

# Don't ask for reviews of the generated code.
ignore_patterns:
  - generated/**/lib/*.dart
  - generated/**/{LICENSE,README.md,analysis_options.yaml,pubspec.yaml}
